[package]
name = "piggybank"
version = "0.5.5"
authors = ["Julian Ćwirko <julian.cwirko@gmail.com>"]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.multiversx-sc]
version = "0.45.2"

[dev-dependencies.multiversx-sc-scenario]
version = "0.45.2"
