[package]
name = "piggybank-meta"
version = "0.5.4"
authors = ["Julian Ćwirko <julian.cwirko@gmail.com>"]
edition = "2021"
publish = false

[dependencies.piggybank]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.45.1"
